[33] Add logic to use questionGroup in converter
bobbylej/grow-me pull request #33
Opened 2021-06-12 13:54 UTC by lukaszzadamczyk

- Add logic to use QuestionGroup component in markdown converter
- Add logic to use QuestionItem component in markdown converter

2021-06-12 20:11 UTC, bobbylej requested changes

2021-06-12 20:11 UTC, bobbylej commented on src/app/shared/components/QuestionGroup/QuestionGroup.tsx
> +}: React.PropsWithChildren<any>): ReactElement => {
Let's change type `: React.PropsWithChildren<any>` to `: { children?: React.ReactNode; }`, because this `any` type results with error on deploy 😉

2021-06-12 20:11 UTC, bobbylej commented on src/app/shared/components/QuestionItem/QuestionItem.tsx
> +// import { CheckBoxCustom } from 'app/shared/components/CheckBoxCustom/CheckBoxCustom';
remove commented code 🙏

2021-06-12 20:21 UTC, lukaszzadamczyk commented on src/app/shared/components/QuestionGroup/QuestionGroup.tsx
> +}: React.PropsWithChildren<any>): ReactElement => {
done 👌

2021-06-12 20:21 UTC, lukaszzadamczyk commented on src/app/shared/components/QuestionItem/QuestionItem.tsx
> +// import { CheckBoxCustom } from 'app/shared/components/CheckBoxCustom/CheckBoxCustom';
ready boss ! 😎

2021-06-14 10:00 UTC, bobbylej approved these changes
![](https://media.giphy.com/media/fKbgG8zDPuLh6/giphy.gif)

2021-06-14 13:25 UTC, merged