[38] Change colors in theme
bobbylej/grow-me pull request #38
Opened 2021-07-13 11:03 UTC by bobbylej

- Change color to monochromatic
- Use dark or light mode based on the browser preferences

2021-07-19 14:19 UTC, lukaszzadamczyk approved these changes

2021-07-21 13:34 UTC, lukaszzadamczyk requested changes

2021-07-21 13:34 UTC, lukaszzadamczyk commented on src/app/shared/constants/theme.ts
> +      dark: '#237a69',
here should be shades of red? 🧐

2021-07-21 16:57 UTC, bobbylej commented on src/app/shared/constants/theme.ts
> +      dark: '#237a69',
I've changed them to monochromatic green colors 😉 🟢

2021-07-21 23:33 UTC, lukaszzadamczyk approved these changes

2021-08-08 13:35 UTC, lukaszzadamczyk approved these changes
the last one ? 😁😂

2021-08-15 12:34 UTC, bobbylej commented
> the last one ? 😁😂

dunno 🤷

2021-08-23 17:13 UTC, merged